Bump modules iam-role to v0.14.0 and sns-topic to v0.20.1
cloudposse/terraform-aws-config pull request #42
Opened 2021-12-08 21:56 UTC by milldr

## what
* Update the modules versions for iam-role and sns-topic

## why
* Required to resolve downstream errors with the `compliance` components

## references
* closes #41 
* closes #21

2021-12-08 22:02 UTC, milldr commented
/test all

2021-12-08 22:04 UTC, milldr commented
this PR includes `make github/init` with the manual fix for `.github/auto-release.yml`

2021-12-08 23:36 UTC, milldr commented
/test all

2021-12-09 01:46 UTC, nitrocode approved these changes

2021-12-09 21:31 UTC, nitrocode submitted a review, later dismissed

2021-12-09 21:48 UTC, Nuru requested changes
We really want to avoid breaking changes if possible.

2021-12-09 21:48 UTC, Nuru commented on variables.tf
> +    raw_message_delivery   = bool
This is a breaking change. Is it really necessary?

2021-12-10 00:39 UTC, milldr commented
/test all

2021-12-10 01:19 UTC, milldr commented
/test all

2021-12-10 01:35 UTC, milldr commented
/test all

2021-12-10 05:44 UTC, merged